### ISSUE TITLE
Can't load the modules

### ISSUE THREAD

**Issue by stanlee321** [IWESUniKS/pandapower#1]
Hi, I trying to load the API into a simple jupyter notebook but I can't figure out the way of load the modules, for example...

`import` pandapower as pp
import sys
net = `pp.create_empty_network()`

then the next error apear:

AttributeError                            Traceback (most recent call last)
<ipython-input-17-49153273d1ee> in <module>()
      1 import pandapower as pp
      2 import sys
----> 3 net = pp.create_empty_network()

AttributeError: 'module' object has no attribute 'create_empty_network'

In the containing folder I can't find any file that contain the modules or the way of install them, can you help me with this please?.

**Comment by IWESUniKS** [comment]
Hi,

I am sorry, the pandapower code is not yet available on github since our legal department has not yet signed off on us publishing the code. As soon as we have the go-ahead and publish we will let you know.

**Comment by IWESUniKS** [comment]
pandapower is now open source, see www.uni-kassel.de/go/pandapower
